version: '3.8'
services:
  redis_db:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - nesjs-network
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=luckydb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - nesjs-network
volumes:
  db:
    driver: local
networks:
  nesjs-network: