export const jwtConstants = {
    //TODO: USAR ENV VARIABLE
    secret: 'secretKey',
}

export const ERROR_CODES = {
    INTERNAL_SERVER_ERROR_EXCEPTION: 'INTERNAL_SERVER_ERROR_EXCEPTION',
    UNAUTHORIZED_EXCEPTION: 'UNAUTHORIZED_EXCEPTION',
    PROFILE_NOT_FOUND_EXCEPTION: 'PROFILE_NOT_FOUND_EXCEPTION',
    USER_NOT_FOUND_EXCEPTION: 'USER_NOT_FOUND_EXCEPTION',
    CREATE_USER_EXCEPTION: 'CREATE_USER_EXCEPTION',
    REGISTER_EXCEPTION: 'REGISTER_EXCEPTION',
    PARAMETERS_EXCEPTION: 'PARAMETERS_EXCEPTION'
}